from enum import StrEnum


class NaturezaFinanceira(StrEnum):
    REMUNERATORIA = "REMUNERATORIA"
    REFLEXA = "REFLEXA"
    FUNDIARIA = "FUNDIARIA"
    INDENIZATORIA = "INDENIZATORIA"
    ATUALIZACAO = "ATUALIZACAO"
    OUTRA = "OUTRA"
