from enum import StrEnum


class TipoEventoContratual(StrEnum):
    ADMISSAO = "ADMISSAO"
    REAJUSTE = "REAJUSTE"
    PROMOCAO = "PROMOCAO"
    ALTERACAO_JORNADA = "ALTERACAO_JORNADA"
    ALTERACAO_DIVISOR = "ALTERACAO_DIVISOR"
    AFASTAMENTO = "AFASTAMENTO"
    RETORNO = "RETORNO"
    RESCISAO = "RESCISAO"
    OUTRO = "OUTRO"
