from enum import StrEnum


class StatusPlanoCalculo(StrEnum):
    RASCUNHO = "RASCUNHO"
    EM_REVISAO = "EM_REVISAO"
    HOMOLOGADO = "HOMOLOGADO"
    SUSPENSO = "SUSPENSO"
    SUBSTITUIDO = "SUBSTITUIDO"


class NaturezaVerba(StrEnum):
    SALARIAL = "SALARIAL"
    INDENIZATORIA = "INDENIZATORIA"
    TRIBUTARIA = "TRIBUTARIA"
    PREVIDENCIARIA = "PREVIDENCIARIA"
    FGTS = "FGTS"
    HONORARIOS = "HONORARIOS"
    CUSTAS = "CUSTAS"
    OUTRA = "OUTRA"
