from enum import StrEnum


class FinalidadeCalculo(StrEnum):
    ESTIMATIVA_PETICAO_INICIAL = "ESTIMATIVA_PETICAO_INICIAL"
    SIMULACAO_NEGOCIACAO = "SIMULACAO_NEGOCIACAO"
    LIQUIDACAO_SENTENCA = "LIQUIDACAO_SENTENCA"
    IMPUGNACAO_CALCULOS = "IMPUGNACAO_CALCULOS"
    ATUALIZACAO_EXECUCAO = "ATUALIZACAO_EXECUCAO"
    ACORDO = "ACORDO"


class TipoOrigemPlano(StrEnum):
    PREMISSA_PROFISSIONAL = "PREMISSA_PROFISSIONAL"
    TITULO_EXECUTIVO = "TITULO_EXECUTIVO"


class TipoCenario(StrEnum):
    CONSERVADOR = "CONSERVADOR"
    PROVAVEL = "PROVAVEL"
    INTEGRAL = "INTEGRAL"
    PERSONALIZADO = "PERSONALIZADO"


class GrauConfianca(StrEnum):
    BAIXO = "BAIXO"
    MEDIO = "MEDIO"
    ALTO = "ALTO"
    DOCUMENTAL = "DOCUMENTAL"
