from enum import StrEnum


class TipoSecaoRelatorio(StrEnum):
    CAPA = "CAPA"
    SUMARIO = "SUMARIO"
    INTRODUCAO = "INTRODUCAO"
    DADOS_PROCESSUAIS = "DADOS_PROCESSUAIS"
    METODOLOGIA = "METODOLOGIA"
    LINHA_TEMPO = "LINHA_TEMPO"
    CRITERIOS_JURIDICOS = "CRITERIOS_JURIDICOS"
    MEMORIA_CALCULO = "MEMORIA_CALCULO"
    DEMONSTRATIVO_FINANCEIRO = "DEMONSTRATIVO_FINANCEIRO"
    ATUALIZACAO_MONETARIA = "ATUALIZACAO_MONETARIA"
    CONCLUSAO = "CONCLUSAO"
    ASSINATURA_TECNICA = "ASSINATURA_TECNICA"
