from enum import StrEnum


class TipoSecaoMemoria(StrEnum):
    IDENTIFICACAO = "IDENTIFICACAO"
    PREMISSAS = "PREMISSAS"
    LINHA_TEMPO = "LINHA_TEMPO"
    COMPETENCIAS = "COMPETENCIAS"
    DEMONSTRATIVO = "DEMONSTRATIVO"
    CONSOLIDACAO = "CONSOLIDACAO"
    OBSERVACOES = "OBSERVACOES"
    CONCLUSAO = "CONCLUSAO"
