from enum import StrEnum


class TipoBaseCalculo(StrEnum):
    SALARIO_CONTRATUAL = "SALARIO_CONTRATUAL"
    SALARIO_NORMATIVO = "SALARIO_NORMATIVO"
    REMUNERACAO_MEDIA = "REMUNERACAO_MEDIA"
    REMUNERACAO_RECONHECIDA = "REMUNERACAO_RECONHECIDA"
    BASE_ARBITRADA = "BASE_ARBITRADA"
    OUTRA = "OUTRA"
