from enum import StrEnum


class TipoRelatorio(StrEnum):
    MEMORIA_CALCULO = "MEMORIA_CALCULO"
    RELATORIO_TECNICO = "RELATORIO_TECNICO"
    PARECER_TECNICO = "PARECER_TECNICO"
    RELATORIO_SINTETICO = "RELATORIO_SINTETICO"
