from enum import StrEnum


class TipoMarcoTemporal(StrEnum):
    INICIO_PERIODO = "INICIO_PERIODO"
    EVENTO_CONTRATUAL = "EVENTO_CONTRATUAL"
    ALTERACAO_ESTADO = "ALTERACAO_ESTADO"
    INATIVIDADE = "INATIVIDADE"
    RETOMADA = "RETOMADA"
    RESCISAO = "RESCISAO"
    FIM_PERIODO = "FIM_PERIODO"
