from enum import StrEnum

class FaseProcessual(StrEnum):
    CONHECIMENTO = "CONHECIMENTO"
    LIQUIDACAO = "LIQUIDACAO"
    EXECUCAO = "EXECUCAO"
    ENCERRADO = "ENCERRADO"

class StatusProcesso(StrEnum):
    CADASTRADO = "CADASTRADO"
    EM_ANALISE = "EM_ANALISE"
    TITULO_EM_ESTRUTURACAO = "TITULO_EM_ESTRUTURACAO"
    PRONTO_PARA_CALCULO = "PRONTO_PARA_CALCULO"
    EM_CALCULO = "EM_CALCULO"
    CALCULADO = "CALCULADO"
    HOMOLOGADO = "HOMOLOGADO"
    EM_EXECUCAO = "EM_EXECUCAO"
    ENCERRADO = "ENCERRADO"
    ARQUIVADO = "ARQUIVADO"
