from enum import StrEnum

class TipoFato(StrEnum):
    CONTRATUAL = "CONTRATUAL"
    REMUNERATORIO = "REMUNERATORIO"
    JORNADA = "JORNADA"
    PROCESSUAL = "PROCESSUAL"
    EXECUTIVO = "EXECUTIVO"
    OUTRO = "OUTRO"

class StatusPedido(StrEnum):
    IDENTIFICADO = "IDENTIFICADO"
    CONTESTADO = "CONTESTADO"
    DEFERIDO = "DEFERIDO"
    DEFERIDO_PARCIALMENTE = "DEFERIDO_PARCIALMENTE"
    INDEFERIDO = "INDEFERIDO"
    PREJUDICADO = "PREJUDICADO"

class AcaoComando(StrEnum):
    DEFERIR = "DEFERIR"
    INDEFERIR = "INDEFERIR"
    DEFERIR_PARCIALMENTE = "DEFERIR_PARCIALMENTE"
    CONDENAR = "CONDENAR"
    DECLARAR = "DECLARAR"
    LIMITAR = "LIMITAR"
    EXCLUIR = "EXCLUIR"
    DEDUZIR = "DEDUZIR"
    COMPENSAR = "COMPENSAR"
    RECOLHER = "RECOLHER"
    RETIFICAR = "RETIFICAR"

class StatusCriterio(StrEnum):
    RASCUNHO = "RASCUNHO"
    EM_REVISAO = "EM_REVISAO"
    HOMOLOGADO = "HOMOLOGADO"
    SUSPENSO = "SUSPENSO"
    SUBSTITUIDO = "SUBSTITUIDO"
